package de.florianmichael.betapackets.model.potioneffect;

public enum PotionEffectType {

    ABSORPTION,
    BAD_OMEN,
    BLINDNESS,
    CONDUIT_POWER,
    DARKNESS,
    DOLPHINS_GRACE,
    FIRE_RESISTANCE,
    GLOWING,
    HASTE,
    INSTANT_HEALTH,
    HERO_OF_THE_VILLAGE,
    HUNGER,
    INSTANT_DAMAGE,
    HEALTH_BOOST,
    INVISIBILITY,
    JUMP_BOOST,
    LEVITATION,
    LUCK,
    MINING_FATIGUE,
    NAUSEA,
    NIGHT_VISION,
    POISON,
    REGENERATION,
    RESISTANCE,
    SATURATION,
    SLOW_FALLING,
    SLOWNESS,
    SPEED,
    STRENGTH,
    UNLUCK,
    WATER_BREATHING,
    WEAKNESS,
    WITHER;

}
