/*
 * This file is part of BetaPackets - https://github.com/BetaPackets/BetaPackets
 * Copyright (C) 2023 FlorianMichael/EnZaXD
 * Copyright (C) 2023 DietrichPaul and contributors
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.betapackets.betapackets.model.particle;

public enum ParticleType {

    AMBIENT_ENTITY_EFFECT,
    ANGRY_VILLAGER,
    ASH,
    BLOCK,
    BLOCK_MARKER,
    BUBBLE,
    BUBBLE_COLUMN_UP,
    BUBBLE_POP,
    CAMPFIRE_COSY_SMOKE,
    CAMPFIRE_SIGNAL_SMOKE,
    CHERRY_LEAVES,
    CLOUD,
    COMPOSTER,
    CRIMSON_SPORE,
    CRIT,
    CURRENT_DOWN,
    DAMAGE_INDICATOR,
    DOLPHIN,
    DRAGON_BREATH,
    DRIPPING_DRIPSTONE_LAVA,
    DRIPPING_DRIPSTONE_WATER,
    DRIPPING_HONEY,
    DRIPPING_LAVA,
    DRIPPING_OBSIDIAN_TEAR,
    DRIPPING_WATER,
    DUST,
    DUST_COLOR_TRANSITION,
    EFFECT,
    EGG_CRACK,
    ELDER_GUARDIAN,
    ELECTRIC_SPARK,
    ENCHANT,
    ENCHANTED_HIT,
    END_ROD,
    ENTITY_EFFECT,
    EXPLOSION,
    EXPLOSION_EMITTER,
    FALLING_DRIPSTONE_LAVA,
    FALLING_DRIPSTONE_WATER,
    FALLING_DUST,
    FALLING_HONEY,
    FALLING_LAVA,
    FALLING_NECTAR,
    FALLING_OBSIDIAN_TEAR,
    FALLING_SPORE_BLOSSOM,
    FALLING_WATER,
    FIREWORK,
    FISHING,
    FLAME,
    FLASH,
    GLOW,
    GLOW_SQUID_INK,
    HAPPY_VILLAGER,
    HEART,
    INSTANT_EFFECT,
    ITEM,
    ITEM_SLIME,
    ITEM_SNOWBALL,
    LANDING_HONEY,
    LANDING_LAVA,
    LANDING_OBSIDIAN_TEAR,
    LARGE_SMOKE,
    LAVA,
    MYCELIUM,
    NAUTILUS,
    NOTE,
    POOF,
    PORTAL,
    RAIN,
    REVERSE_PORTAL,
    SCRAPE,
    SCULK_CHARGE,
    SCULK_CHARGE_POP,
    SCULK_SOUL,
    SHRIEK,
    SMALL_FLAME,
    SMOKE,
    SNEEZE,
    SNOWFLAKE,
    SONIC_BOOM,
    SOUL,
    SOUL_FIRE_FLAME,
    SPIT,
    SPLASH,
    SPORE_BLOSSOM_AIR,
    SQUID_INK,
    SWEEP_ATTACK,
    TOTEM_OF_UNDYING,
    UNDERWATER,
    DEPTHSUSPEND,
    VIBRATION,
    WARPED_SPORE,
    WAX_OFF,
    WAX_ON,
    WHITE_ASH,
    WITCH,
    FOOTSTEP,
    BARRIER,
    LIGHT,
    ITEMCRACK,
    BLOCKCRACK,
    BLOCKDUST;

}
